version: 2
registries:
  fortawesome:
    type: npm-registry
    url: https://npm.fontawesome.com/
    token: ${{secrets.FONTAWESOME_NPM_AUTH_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/modules/ui/demo/"
    registries:
      - fortawesome
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "npm dependencies"
