version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/modules/ui/demo/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "npm dependencies"
